[package]
name = "binpacking-exercise"
version = "0.1.0"
edition = "2024"

[dependencies]
russcip = { git = "https://github.com/scipopt/russcip.git", branch = "bin-packing-example", features= ["bundled"] }
rand = "0.9.1"